spring:
  application:
    name: jogging
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
server:
  port: 9000
webber:
  app:
    jwtSecret: Zm9vYmFy
    jwtExpirationMinutes: 180
