spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=true;MODE=MySQL
    username: sa
    password: sa

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: false
    defer-datasource-initialization: true

    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
  sql:
    init.mode: always
