spring:
  application:
    name: jogging
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost/jlweb
    username: jlweb58
    password: Wutzi!
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
  profiles:
    active: localhost
server:
  port: 9000
webber:
  app:
    jwtSecret: foobar
    jwtExpirationMs: 2000000
