spring:
  application:
    name: jogging
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost/jlweb
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
server:
  port: 9000
webber:
  app:
    jwtSecret: Zm9vYmFy
    jwtExpirationMinutes: 180
