spring:
  application:
    name: jogging
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
  profiles:
    active: localhost
  resources:
    static-locations: file:src/main/resources/templates
server:
  port: 9000